### ISSUE TITLE
Alter Availability Feature to enforce start and end time in LocalTime, HH:mm format

### ISSUE THREAD

**Issue by whitesnowx** [AY2324S2-CS2103-F08-3/tp#124]
- [ ] Amend Availability Feature #120 
- [ ] Update Test Data #120 
- [ ] Update UserGuide Examples #123
